# --- COMPILER & PATHS ---
CXX      = clang++
CC       = clang
BREW_INC = /opt/homebrew/include
BREW_LIB = /opt/homebrew/lib

# --- DIRECTORIES ---
BUILD_DIR = build
SRC_DIR   = src

# --- FLAGS ---
# -MMD and -MP are the "magic" flags that track header dependencies
CXXFLAGS = -std=c++17 -Wall -Wextra -MMD -MP -I./include -I./imgui -I./imgui/backends -I$(BREW_INC)
CFLAGS   = -Wall -I./include -I$(BREW_INC)
LDFLAGS  = -L$(BREW_LIB) -lglfw -framework OpenGL -framework Cocoa -framework IOKit -framework CoreVideo

# --- FILES ---
TARGET   = $(BUILD_DIR)/game

# 1. Project files in src/
PROJECT_SRCS = $(SRC_DIR)/main.cpp $(SRC_DIR)/camera.cpp $(SRC_DIR)/shader.cpp $(SRC_DIR)/stb_image.cpp
PROJECT_OBJS = $(PROJECT_SRCS:$(SRC_DIR)/%.cpp=$(BUILD_DIR)/%.o)

# 2. ImGui Core files in imgui/
IMGUI_SRCS = imgui/imgui.cpp imgui/imgui_draw.cpp imgui/imgui_widgets.cpp imgui/imgui_tables.cpp
IMGUI_OBJS = $(IMGUI_SRCS:imgui/%.cpp=$(BUILD_DIR)/imgui_%.o)

# 3. ImGui Backends in imgui/backends/
BACKEND_SRCS = imgui/backends/imgui_impl_glfw.cpp imgui/backends/imgui_impl_opengl3.cpp
BACKEND_OBJS = $(BACKEND_SRCS:imgui/backends/%.cpp=$(BUILD_DIR)/%.o)

# 4. C files
GLAD_OBJ = $(BUILD_DIR)/glad.o

# Combine all objects
OBJ = $(PROJECT_OBJS) $(IMGUI_OBJS) $(BACKEND_OBJS) $(GLAD_OBJ)

# Collect all dependency files generated by -MMD
DEPS = $(OBJ:.o=.d)

# --- RULES ---
all: $(TARGET)

$(TARGET): $(OBJ)
	$(CXX) $(OBJ) -o $(TARGET) $(LDFLAGS)

# Include the generated dependency files (this is what makes it work!)
-include $(DEPS)

# Rule for Project files (src/*.cpp)
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp | $(BUILD_DIR)
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Rule for Glad (src/glad.c)
$(BUILD_DIR)/glad.o: $(SRC_DIR)/glad.c | $(BUILD_DIR)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

# Rule for ImGui Core (imgui/*.cpp)
$(BUILD_DIR)/imgui_%.o: imgui/%.cpp | $(BUILD_DIR)
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Rule for ImGui Backends (imgui/backends/*.cpp)
$(BUILD_DIR)/%.o: imgui/backends/%.cpp | $(BUILD_DIR)
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

clean:
	rm -rf $(BUILD_DIR)

run: all
	./$(TARGET)

.PHONY: all clean run
